<?php
use Laminas\View\View;

/**
 * @var $this View
 */
?>
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Swagger UI</title>
<link rel="stylesheet" type="text/css" href="./swagger-ui.css">
<link rel="icon" type="image/png" href="./favicon-32x32.png"
	sizes="32x32" />
<link rel="icon" type="image/png" href="./favicon-16x16.png"
	sizes="16x16" />
<style>
html {
	box-sizing: border-box;
	overflow: -moz-scrollbars-vertical;
	overflow-y: scroll;
}

*, *:before, *:after {
	box-sizing: inherit;
}

body {
	margin: 0;
	background: #fafafa;
}
</style>
</head>
<body>
	<div id="swagger-ui"></div>
	<script type="text/javascript" src="<?=$this->url('home')?>swagger-ui-bundle.js"> </script>
	<script type="text/javascript" src="<?=$this->url('home')?>swagger-ui-standalone-preset.js"> </script>
	<script type="text/javascript" src="<?=$this->url('home')?>spec.js"> </script>
	<script type="text/javascript">
	window.onload = function() {
		// Begin Swagger UI call region
		const ui = SwaggerUIBundle({
			//url: "https://petstore.swagger.io/v2/swagger.json",
			spec : spec,
			dom_id: '#swagger-ui',
			deepLinking: true,
			presets: [
				SwaggerUIBundle.presets.apis,
				SwaggerUIStandalonePreset
			],
			plugins: [
				SwaggerUIBundle.plugins.DownloadUrl
			],
			layout: "StandaloneLayout"
		})
		// End Swagger UI call region
		window.ui = ui
	}
	</script>
</body>
</html>

