<?php
use Laminas\View\View;

/**
 * @var $this View
 */
echo $this->headTitle('Home');
?>

<div class="row">
    <div class="col-md-4">
        <h2><span class="mezzio-green">
           Kubernetes Reading
        </span></h2>
		<?=$this->kubernetesReadingStatusBlock?>
    </div>
    <div class="col-md-4">
        <h2><span class="mezzio-green">
            Queue Writing            
        </span></h2>
		<?=$this->kubernetesReadingStatusBlock?>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2><span class="mezzio-green">
            Queue Reading            
        </span></h2>
		<?=$this->queueReadingStatusBlock?>
    </div>    
    <div class="col-md-4">
        <h2><span class="mezzio-green">
            Fluentd Writing            
        </span></h2>
		<?=$this->fluentdWritingStatusBlock?>
    </div>    
</div>